name: mdl
description: Material Design Lite for Dart
version: 1.14.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: http://www.material-design-lite.pub

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  browser: ^0.10.0

  intl: ^0.12.0
  validate: ^1.0.0
  browser_detect: ^1.0.0

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.1.0
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  route_hierarchical: ^0.6.0

  mustache:
    #^0.2.0
    #path: /Volumes/Daten/DevLocal/DevDart/Test/mustache
    # ^0.2.0
    git: https://github.com/MikeMitterer/mustache

  dnd: ^0.3.0

  di: '^3.3.0'

  barback: ^0.15.0

  reflectable: '^0.4.0'

dev_dependencies:
  test: any
  args: any
  material_icons: any
  path: any
  grinder: any

transformers:
  - di
  - mdl

  - $dart2js:
      commandLineOptions: [--enable-experimental-mirrors]


